version: '3.8'

services:
  frontend:
    image: node:latest
    container_name: nextjs_frontend
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"